baseURL = "http://localhost:1313"

[params.services]
googleAnalyticsId = ""
googleTagManagerId = "GTM-KZND9MH"
googleAdsId = ""
googleAdsenseId = ""
googleAdsenseAdSlotId = ""
googleAdsenseLoad = ""
googleAdsConversionId = ""
googleAdsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.cdn]
provider = "cloudinary"
[params.cloudinary]
host = "https://res.cloudinary.com/litetrail/"
version = ""
