baseURL = "http://localhost:1313"

[params.services]
analyticsId = ""
adwordsId = ""
adsenseId = ""
adsenseAdSlotId = ""
adsenseLoad = ""
adwordsConversionId = ""
adwordsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.cdn]
provider = "cloudinary"
[params.cloudinary]
host = "https://res.cloudinary.com/litetrail/"
version = ""
